"use client";
import Link from "next/link";
import { useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { ArrowRight, KeyRound, Waves } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { Button } from "./ui/button";
import { Card, CardContent } from "./ui/card";
import { Input, Label } from "./ui/form";

export function AuthForm({ mode }: { mode: "login"|"register" }) {
  const router=useRouter(), params=useSearchParams(); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");const fd=new FormData(e.currentTarget);try{const s=createClient();const email=String(fd.get("email")),password=String(fd.get("password"));if(mode==="register"){const {error}=await s.auth.signUp({email,password,options:{data:{full_name:String(fd.get("name"))}}});if(error)throw error;setMessage("Account created. Check your email if confirmation is enabled.");}else{const {error}=await s.auth.signInWithPassword({email,password});if(error)throw error;router.replace(params.get("next")||"/dashboard");router.refresh();}}catch(err){setMessage(err instanceof Error?err.message:"Authentication failed.");}finally{setBusy(false)}}
  async function reset(){const email=(document.getElementById("email") as HTMLInputElement)?.value;if(!email){setMessage("Enter your email first.");return;}try{const s=createClient();const {error}=await s.auth.resetPasswordForEmail(email,{redirectTo:`${location.origin}/profile`});if(error)throw error;setMessage("Password reset email requested.");}catch(err){setMessage(err instanceof Error?err.message:"Reset failed.");}}
  return <main className="grid-texture min-h-[calc(100vh-4rem)] py-12"><div className="page-shell grid items-center gap-10 lg:grid-cols-2"><div className="hidden lg:block"><span className="grid size-14 place-items-center rounded-2xl bg-[var(--primary)] text-white"><Waves/></span><h1 className="font-display mt-6 max-w-md text-5xl font-black leading-tight">A clearer signal when streets turn uncertain.</h1><p className="mt-4 max-w-md text-[var(--muted-fg)]">Your account protects private emergency details and keeps your reports, alerts, and notifications together.</p></div><Card className="mx-auto w-full max-w-md"><CardContent className="p-6 sm:p-8"><KeyRound className="text-[var(--secondary)]"/><h1 className="font-display mt-4 text-3xl font-black">{mode==="login"?"Welcome back":"Create your account"}</h1><p className="mt-2 text-sm text-[var(--muted-fg)]">{mode==="login"?"Sign in to report and manage alerts.":"Join the community flood monitoring network."}</p><form onSubmit={submit} className="mt-7 space-y-4">{mode==="register"&&<div><Label htmlFor="name">Full name</Label><Input id="name" name="name" minLength={2} maxLength={100} required autoComplete="name"/></div>}<div><Label htmlFor="email">Email</Label><Input id="email" name="email" type="email" required autoComplete="email"/></div><div><Label htmlFor="password">Password</Label><Input id="password" name="password" type="password" minLength={8} maxLength={72} required autoComplete={mode==="login"?"current-password":"new-password"}/></div>{message&&<div role="status" className="rounded-xl bg-[var(--muted)] p-3 text-sm">{message}</div>}<Button className="w-full" disabled={busy}>{busy?"Please wait…":mode==="login"?"Log in":"Create account"}<ArrowRight size={17}/></Button></form>{mode==="login"&&<button onClick={reset} className="mt-4 text-sm font-bold text-[var(--primary)] hover:underline">Forgot password?</button>}<p className="mt-6 text-sm text-[var(--muted-fg)]">{mode==="login"?"No account yet? ":"Already registered? "}<Link className="font-bold text-[var(--primary)] hover:underline" href={mode==="login"?"/register":"/login"}>{mode==="login"?"Register":"Log in"}</Link></p></CardContent></Card></div></main>;
}
