"use client";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import L from "leaflet";
import { createClient } from "@/lib/supabase/client";
import type { FloodDepth, FloodReport } from "@/lib/types";
import { evaluatePassability, type Passability } from "@/lib/passability";
import { labelize, timeAgo } from "@/lib/utils";
import { Button } from "./ui/button";
import { Input, Select } from "./ui/form";
import { StatusPill } from "./status-pill";
import { Crosshair, RefreshCw, Search, Signal, SignalZero, X } from "lucide-react";

type Rule={vehicle_types:{slug:string;name:string};caution_depth:FloodDepth;max_depth:FloodDepth};
const colors:Record<Passability,string>={passable:"#16a34a",caution:"#d97706",hazardous:"#dc2626",unknown:"#64748b"};
export default function MapCanvas(){
 const el=useRef<HTMLDivElement>(null),map=useRef<L.Map|null>(null),layer=useRef<L.LayerGroup|null>(null);const [reports,setReports]=useState<FloodReport[]>([]),[rules,setRules]=useState<Rule[]>([]),[vehicle,setVehicle]=useState("sedan"),[depth,setDepth]=useState("all"),[selected,setSelected]=useState<FloodReport|null>(null),[status,setStatus]=useState<"connecting"|"live"|"offline">("connecting"),[error,setError]=useState("");
 const load=useCallback(async()=>{try{setError("");const [a,b]=await Promise.all([fetch(`/api/reports?depth=${depth}`),fetch("/api/passability")]);const aj=await a.json(),bj=await b.json();if(!a.ok)throw new Error(aj.error);setReports(aj.data||[]);if(b.ok)setRules(bj.data||[]);}catch(e){setError(e instanceof Error?e.message:"Map data unavailable")}},[depth]);
 useEffect(()=>{if(!el.current||map.current)return;map.current=L.map(el.current,{zoomControl:false}).setView([12.8797,121.7740],6);L.control.zoom({position:"bottomright"}).addTo(map.current);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',maxZoom:19}).addTo(map.current);layer.current=L.layerGroup().addTo(map.current);return()=>{map.current?.remove();map.current=null}},[]);
 useEffect(()=>{load()},[load]);
 useEffect(()=>{let channel:ReturnType<ReturnType<typeof createClient>["channel"]>|undefined;try{const s=createClient();channel=s.channel("public-flood-map").on("postgres_changes",{event:"*",schema:"public",table:"flood_reports"},()=>load()).subscribe(x=>setStatus(x==="SUBSCRIBED"?"live":x==="CHANNEL_ERROR"||x==="TIMED_OUT"?"offline":"connecting"));}catch{setStatus("offline")}return()=>{if(channel)channel.unsubscribe()}},[load]);
 const rule=rules.find(r=>r.vehicle_types.slug===vehicle);const pass=(r:FloodReport)=>rule?evaluatePassability(r.depth,rule.caution_depth,rule.max_depth,(Date.now()-new Date(r.observed_at).getTime())/36e5):"unknown";
 useEffect(()=>{if(!layer.current)return;layer.current.clearLayers();reports.forEach(r=>{const p=pass(r);const icon=L.divIcon({className:"",html:`<div class="marker-dot" style="background:${colors[p]}" aria-label="${p}"></div>`,iconSize:[22,22],iconAnchor:[11,11]});L.marker([r.latitude,r.longitude],{icon}).on("click",()=>setSelected(r)).addTo(layer.current!);})},[reports,rule]);
 const locate=()=>navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>map.current?.setView([p.coords.latitude,p.coords.longitude],15),e=>setError(`Location unavailable: ${e.message}`),{enableHighAccuracy:true,timeout:10000}):setError("Geolocation is not supported.");
 async function search(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const q=String(new FormData(e.currentTarget).get("q"));try{const res=await fetch(`https://nominatim.openstreetmap.org/search?format=json&limit=1&q=${encodeURIComponent(q)}`);const data=await res.json();if(data[0])map.current?.setView([Number(data[0].lat),Number(data[0].lon)],14);else setError("Location not found.");}catch{setError("Search is temporarily unavailable.")}}
 return <div className="grid gap-4 lg:grid-cols-[1fr_320px]">
  <section className="overflow-hidden rounded-2xl border border-[var(--border)] bg-[var(--card)] shadow-[var(--shadow)]"><div className="flex flex-col gap-3 border-b border-[var(--border)] p-3 sm:flex-row"><form onSubmit={search} className="flex flex-1 gap-2"><Input name="q" aria-label="Search location" placeholder="Search city or barangay"/><Button size="icon" variant="outline" aria-label="Search"><Search size={18}/></Button></form><div className="flex gap-2"><Select aria-label="Vehicle type" value={vehicle} onChange={e=>setVehicle(e.target.value)}>{rules.length?rules.map(r=><option value={r.vehicle_types.slug} key={r.vehicle_types.slug}>{r.vehicle_types.name}</option>):<option value="sedan">Vehicle rules unavailable</option>}</Select><Button size="icon" variant="outline" onClick={locate} aria-label="Use current location"><Crosshair size={18}/></Button></div></div>{error&&<div role="alert" className="border-b border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</div>}<div ref={el} className="h-[60vh] min-h-[430px] w-full" aria-label="Flood report map"/></section>
  <aside className="space-y-4"><div className="rounded-2xl border border-[var(--border)] bg-[var(--card)] p-4 shadow-[var(--shadow)]"><div className="flex items-center justify-between"><p className="font-display font-bold">Map controls</p><span className="flex items-center gap-1.5 text-xs font-bold text-[var(--muted-fg)]">{status==="live"?<Signal size={14} className="text-emerald-500"/>:<SignalZero size={14}/>} {status}</span></div><label className="mt-4 block text-xs font-bold">Flood depth filter</label><Select className="mt-1" value={depth} onChange={e=>setDepth(e.target.value)}>{["all","none","ankle","calf","knee","waist","chest","unknown"].map(x=><option key={x} value={x}>{labelize(x)}</option>)}</Select><Button className="mt-3 w-full" variant="outline" onClick={load}><RefreshCw size={15}/>Refresh reports</Button><div className="mt-5 border-t border-[var(--border)] pt-4"><p className="text-xs font-bold">Legend</p><div className="mt-2 grid grid-cols-2 gap-2 text-xs">{Object.entries(colors).map(([k,c])=><span key={k} className="flex items-center gap-2"><i className="size-2.5 rounded-full" style={{background:c}}/>{labelize(k)}</span>)}</div></div></div>
  <div className="rounded-2xl border border-[var(--border)] bg-[var(--card)] p-4 shadow-[var(--shadow)]">{selected?<><div className="flex justify-between gap-2"><StatusPill status={pass(selected)}/><button onClick={()=>setSelected(null)} aria-label="Close report detail"><X size={18}/></button></div><h2 className="font-display mt-4 text-xl font-bold">{selected.location_name}</h2><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-xs text-[var(--muted-fg)]">Depth</dt><dd className="font-bold">{labelize(selected.depth)}</dd></div><div><dt className="text-xs text-[var(--muted-fg)]">Observed</dt><dd className="font-bold">{timeAgo(selected.observed_at)}</dd></div><div><dt className="text-xs text-[var(--muted-fg)]">Verification</dt><dd><StatusPill status={selected.verification_status}/></dd></div><div><dt className="text-xs text-[var(--muted-fg)]">Coordinates</dt><dd className="font-mono text-xs">{selected.latitude.toFixed(4)}, {selected.longitude.toFixed(4)}</dd></div></dl>{selected.description&&<p className="mt-4 text-sm text-[var(--muted-fg)]">{selected.description}</p>}<p className="mt-4 rounded-xl bg-amber-50 p-3 text-xs leading-5 text-amber-950 dark:bg-amber-950 dark:text-amber-100">Conditions can change without warning. Never treat this indicator as a guarantee of safety.</p></>:<div className="py-8 text-center"><p className="font-display font-bold">Select a report marker</p><p className="mt-2 text-sm text-[var(--muted-fg)]">{reports.length?`${reports.length} recent observations loaded.`:"No current reports match the filter."}</p></div>}</div>
  </aside>
 </div>;
}
