"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { LoaderCircle, LogOut, Save, ShieldCheck } from "lucide-react";
import { PageHeader } from "./page-header";
import { Card, CardContent, CardHeader, CardTitle } from "./ui/card";
import { Button } from "./ui/button";
import { Input, Label } from "./ui/form";
import { StatusPill } from "./status-pill";
type Profile={full_name:string;phone:string|null;role:string;created_at:string;email:string};
export function ProfileForm(){const router=useRouter();const [p,setP]=useState<Profile|null>(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");useEffect(()=>{fetch("/api/profile").then(r=>r.json()).then(j=>j.data?setP(j.data):setMsg(j.error))},[]);async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);const r=await fetch("/api/profile",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({full_name:f.get("full_name"),phone:f.get("phone")})});const j=await r.json();setMsg(r.ok?"Profile updated.":j.error);setBusy(false)}async function logout(){await fetch("/api/auth/logout",{method:"POST"});router.push("/");router.refresh()}return <><PageHeader eyebrow="Account settings" title="Your profile" description="Manage contact details. Roles are assigned only by authorized administrators."/>{!p?<div className="grid min-h-64 place-items-center">{msg||<LoaderCircle className="animate-spin"/>}</div>:<div className="grid gap-5 lg:grid-cols-[1fr_320px]"><Card><CardHeader><CardTitle>Personal information</CardTitle></CardHeader><CardContent><form onSubmit={save} className="space-y-4"><div><Label htmlFor="full_name">Full name</Label><Input id="full_name" name="full_name" defaultValue={p.full_name} required minLength={2}/></div><div><Label htmlFor="email">Email</Label><Input id="email" value={p.email} disabled/><p className="mt-1 text-xs text-[var(--muted-fg)]">Managed through Supabase authentication.</p></div><div><Label htmlFor="phone">Phone <span className="font-normal">(optional)</span></Label><Input id="phone" name="phone" type="tel" defaultValue={p.phone||""}/></div>{msg&&<p role="status" className="rounded-xl bg-[var(--muted)] p-3 text-sm">{msg}</p>}<Button disabled={busy}>{busy?<LoaderCircle className="animate-spin"/>:<Save size={17}/>}Save changes</Button></form></CardContent></Card><aside><Card><CardContent className="p-5"><ShieldCheck className="text-[var(--secondary)]"/><p className="mt-4 text-sm text-[var(--muted-fg)]">Access role</p><div className="mt-2"><StatusPill status={p.role}/></div><p className="mt-4 text-xs leading-5 text-[var(--muted-fg)]">Role changes are audited and cannot be performed from your own account.</p><Button variant="outline" className="mt-6 w-full" onClick={logout}><LogOut size={17}/>Sign out</Button></CardContent></Card></aside></div>}</>}
