"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { Bell, ChevronRight, LoaderCircle, MapPinned, RadioTower, Waves } from "lucide-react";
import { PageHeader } from "./page-header";
import { Card, CardContent, CardHeader, CardTitle } from "./ui/card";
import { StatusPill } from "./status-pill";
import { buttonVariants } from "./ui/button";
import { labelize, timeAgo } from "@/lib/utils";
type Data={reportCount:number;alertCount:number;unread:number;profile:{full_name:string;role:string};reports:Array<{id:string;location_name:string;depth:string;observed_at:string;verification_status:string}>;alerts:Array<{id:string;emergency_type:string;status:string;created_at:string}>;notifications:Array<{id:string;title:string;body:string;read_at:string|null;created_at:string}>};
export function UserDashboard(){const [data,setData]=useState<Data|null>(null),[error,setError]=useState("");useEffect(()=>{fetch("/api/dashboard").then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error);setData(j)}).catch(e=>setError(e.message))},[]);if(error)return <div role="alert" className="rounded-2xl bg-red-50 p-5 text-red-900">{error}</div>;if(!data)return <div className="grid min-h-64 place-items-center"><LoaderCircle className="animate-spin"/></div>;return <><PageHeader eyebrow={`${labelize(data.profile.role)} workspace`} title={`Good to see you, ${data.profile.full_name?.split(" ")[0]||"neighbor"}`} description="Review your latest observations, emergency alerts, and account notifications." actions={<Link href="/report" className={buttonVariants()}><Waves size={17}/>New report</Link>}/><div className="grid gap-4 sm:grid-cols-3">{[[Waves,"Flood reports",data.reportCount],[RadioTower,"SOS alerts",data.alertCount],[Bell,"Unread updates",data.unread]].map(([I,l,v])=><Card key={String(l)}><CardContent className="flex items-center gap-4 p-5"><span className="grid size-11 place-items-center rounded-xl bg-[var(--secondary-soft)] text-[var(--secondary)]"><I size={20}/></span><div><p className="text-2xl font-black">{Number(v)}</p><p className="text-xs font-bold text-[var(--muted-fg)]">{String(l)}</p></div></CardContent></Card>)}</div><div className="mt-5 grid gap-5 lg:grid-cols-2"><Card><CardHeader><div className="flex justify-between"><CardTitle>Recent observations</CardTitle><Link href="/map" className="text-sm font-bold text-[var(--primary)]">View map</Link></div></CardHeader><CardContent className="space-y-2">{data.reports.length?data.reports.map(x=><div key={x.id} className="flex items-center justify-between gap-3 rounded-xl border border-[var(--border)] p-3"><div><p className="text-sm font-bold">{x.location_name}</p><p className="mt-1 text-xs text-[var(--muted-fg)]">{labelize(x.depth)} · {timeAgo(x.observed_at)}</p></div><StatusPill status={x.verification_status}/></div>):<Empty icon={MapPinned} text="No flood reports submitted."/>}</CardContent></Card><Card><CardHeader><CardTitle>Emergency & notifications</CardTitle></CardHeader><CardContent className="space-y-2">{data.alerts.map(x=><div key={x.id} className="flex items-center justify-between rounded-xl border border-[var(--border)] p-3"><div><p className="text-sm font-bold">{labelize(x.emergency_type)}</p><p className="text-xs text-[var(--muted-fg)]">{timeAgo(x.created_at)}</p></div><StatusPill status={x.status}/></div>)}{data.notifications.map(x=><div key={x.id} className="rounded-xl bg-[var(--muted)] p-3"><div className="flex items-center justify-between"><p className="text-sm font-bold">{x.title}</p><ChevronRight size={15}/></div><p className="mt-1 text-xs text-[var(--muted-fg)]">{x.body}</p></div>)}{!data.alerts.length&&!data.notifications.length&&<Empty icon={Bell} text="No alerts or notifications."/>}</CardContent></Card></div></>}
function Empty({icon:I,text}:{icon:typeof Bell;text:string}){return <div className="py-10 text-center text-sm text-[var(--muted-fg)]"><I className="mx-auto mb-2"/>{text}</div>}
